name: pytest

on:
  push:

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.4"
          enable-cache: true
          cache-suffix: "optional-suffix"

      - name: Cache FFmpeg
        id: cache-ffmpeg
        uses: actions/cache@v3
        with:
          path: |
            /usr/bin/ffmpeg
            /usr/bin/ffprobe
            /usr/lib/x86_64-linux-gnu/libavcodec*
            /usr/lib/x86_64-linux-gnu/libavformat*
            /usr/lib/x86_64-linux-gnu/libavutil*
            /usr/lib/x86_64-linux-gnu/libswresample*
          key: ${{ runner.os }}-ffmpeg-${{ hashFiles('/usr/bin/ffmpeg') }}

      - name: Install FFmpeg
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo ldconfig

      - name: Install dependencies
        id: install_dependency_from_cache
        continue-on-error: true
        run: |
          uv sync --extra dev

      - name: Run tests with coverage
        run: |
          uv run pytest --cov=. --cov-report=xml --cov-report=term
  
      - name: Upload coverage to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml