name: pytest

on:
  pull_request:

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.4"
          enable-cache: true
          cache-suffix: "optional-suffix"

      - name: Restore FFmpeg from Cache
        uses: actions/cache@v2
        id: cache-ffmpeg
        with:
          path: .ffmpeg
          key: ${{ runner.os }}-ffmpeg-cache-v1
          restore-keys: |
            ${{ runner.os }}-ffmpeg-cache-

      - name: Install FFmpeg
        run: |
          if [ ! -d ".ffmpeg/bin" ]; then
            sudo apt-get update
            sudo apt-get install -y ffmpeg
            mkdir -p .ffmpeg/bin .ffmpeg/lib
            cp $(which ffmpeg) $(which ffprobe) .ffmpeg/bin/
            cp /usr/lib/x86_64-linux-gnu/libav{codec,format,util}*.so* .ffmpeg/lib/
            cp /usr/lib/x86_64-linux-gnu/libswresample*.so* .ffmpeg/lib/
          fi

      - name: Set FFmpeg in PATH
        run: |
          echo "PATH=$PWD/.ffmpeg/bin:$PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$PWD/.ffmpeg/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Cache FFmpeg
        if: steps.cache-ffmpeg.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: .ffmpeg
          key: ${{ runner.os }}-ffmpeg-cache-v1

      - name: Install dependencies
        id: install_dependency_from_cache
        continue-on-error: true
        run: |
          uv sync --extra dev

      - name: Run tests with coverage
        run: |
          uv run pytest --cov=. --cov-report "xml:coverage.xml" --cov-report=term

      - name: Get test cover
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.9
