name: pytest

on:
  push:

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.4"
          enable-cache: true
          cache-suffix: "optional-suffix"

      - name: Install FFmpeg
        id: install_ffmpeg_from_cache
        run: |
          if [ -d ~/.cache/ffmpeg ]; then
            mkdir -p ~/bin
            cp -a ~/.cache/ffmpeg/. ~/bin/
          else
            sudo apt-get update
            sudo apt-get install -y ffmpeg
            mkdir -p ~/.cache/ffmpeg
            cp -a /usr/bin/. ~/.cache/ffmpeg/
            mkdir -p ~/bin
            cp -a /usr/bin/. ~/bin/
          fi

      - name: Install dependencies
        id: install_dependency_from_cache
        continue-on-error: true
        run: |
          uv sync

      - name: Run tests
        run: uv run pytest .
