name: pytest

on:
  pull_request:

jobs:
  tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.4"
          enable-cache: true
          cache-suffix: "optional-suffix"

      - name: Set up FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: 'latest'
          cache: true
  
      - name: Install dependencies
        id: install_dependency_from_cache
        continue-on-error: true
        run: |
          uv sync --extra dev

      - name: Run tests with coverage
        run: |
          uv run pytest --cov=. --cov-report "xml:coverage.xml" --cov-report=term

      - name: Get test cover
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.9
